### ISSUE TITLE
Grunt watch 中的Livereload，如何去配置呢？  菜鸟求教

### ISSUE THREAD

**Issue by nothingrealhappen** [foru17/StaticPage#6]
我目前是在使用ruby gem的方式来使用livereload，看到Grunt有这个功能而且本插件也配置了这个想弃用ruby gem的形式。但是没有找到Grunt livereload配置文件在哪里。

**Comment by foru17** [comment]
grunt wath 配合 chrome liverolad插件就可以了

**Comment by nothingrealhappen** [comment]
已经ok了   非常感谢 ！
